### ISSUE TITLE
inaccurate metrics vs host real time

### ISSUE THREAD

**Issue by haudi1991** [wywywywy/docker_stats_exporter#1]
Hi,

For some hosts docker_stats_exporter metrics are not up to date compare with the current status.

Example: i have 30 containers with status=running and i do not have metrics about them

```
[root@host]# docker ps | wc -l
32
[root@host]#
[root@host]# curl http://localhost:9487/metrics | grep -v "#"

dockerstats_cpu_usage_ratio{name="XXX",id="4f172ac34142"} Nan

[root@host]# docker logs -f docker-exporter --tail 5
ERROR: TypeError: Value is not a valid number: undefined
ERROR: TypeError: Value is not a valid number: undefined
ERROR: TypeError: Value is not a valid number: undefined

```
Thanks

**Comment by wywywywy** [comment]
Sorry I only just noticed your issue.

Are you using HTTP to Socket to connect?  Are you using the Docker image or running the code in Node directly?  What version of Docker engine are you using?

In any case, I've updated the packages to latest.  So can you try again with the newest update please.

**Comment by proggprod** [comment]
I am getting this same error "ERROR: TypeError: Value is not a valid number: undefined"
Don't know if it's the same problem as OP though. 
I haven't successfully got this running yet.
I am trying to run in Docker.
Any tips? Or how to troubleshoot?

**Comment by wywywywy** [comment]
Hi,

1. Are you using HTTP or Socket to connect?
2. Are you using the Docker image or running the code in Node directly?
3. What version of Docker engine are you using?

**Comment by proggprod** [comment]
Thanks for replying. Please excuse my stupidity, I am only exploring all of this for the first time.
I have tried both HTTP and Socket. I think Socket should be the one to work, as I already have Portainer and VSCode talking to three Pi servers running Docker.
I am trying to run this in Docker. I already have the standard node_exporter running and getting those stats to Grafana though Prometheus. So everything should be ready to accept the docker_stats_exporter stats.

The logs for dockerstats say
`> docker_stats_exporter@1.1.0 start /usr/src/app
> node docker_stats_exporter.js
INFO: Connecting to Docker on /var/run/docker.sock...
INFO: Registering Prometheus metrics...
INFO: Starting HTTP server...
INFO: Docker Stats exporter listening on port 9487
ERROR: TypeError: Value is not a valid number: undefined
ERROR: TypeError: Value is not a valid number: undefined
ERROR: TypeError: Value is not a valid number: undefined`


Prometheus seems to be scraping it as it shows up in Grafana, but there are only a few values, non of which seem useful.
![image](https://user-images.githubusercontent.com/81530084/168553467-27ba9f38-3c37-4cc1-b9ae-685b4ec1ddef.png)

My docker-compose looks like
`dockerstats:
    image: wywywywy/docker_stats_exporter:latest
    network_mode: host
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
        DOCKERSTATS_INTERVAL: 15`

**Comment by wywywywy** [comment]
And what version of Docker engine are you using please?

**Comment by wywywywy** [comment]
Also could you run `docker stats` on the host to see what it shows please?

**Comment by proggprod** [comment]
![image](https://user-images.githubusercontent.com/81530084/168559411-12a114ec-9f82-47fa-bf28-e17d80c5b802.png)

**Comment by proggprod** [comment]
bit strange there is no memory info or net io for most containers??

**Comment by wywywywy** [comment]
Ok we need to enable cgroup support in the kernel for memory & network, otherwise the Docker engine won't be able to gather the info.

See here for instructions: https://github.com/moby/moby/issues/18420

**Comment by wywywywy** [comment]
In the mean time I'll update the code, so that even if the cgroups are not enabled, it shouldn't stop working

**Comment by proggprod** [comment]
Thanks.
I don't have a folder /etc/defaults/grub on any of my three Pis, so I can't follow these instructions.
Update what kernel? Nothing is old on these Pi's. Everything is relatively new and updates have been done. 

i tried docker stats on all three Pis to get a comparison.
Some show details, some don't. Not sure what to make of it.
![image](https://user-images.githubusercontent.com/81530084/168578397-b5ef5ff2-9fc4-41ea-b778-fbad7bea2866.png)
![image](https://user-images.githubusercontent.com/81530084/168578442-fdc5b693-6f92-4ac1-80ec-baad48563671.png)
![image](https://user-images.githubusercontent.com/81530084/168578501-f5af4087-fe9a-4d95-a931-716fe35d9fb0.png)

I also tried `ls /sys/fs/cgroup/` and got
`cgroup.controllers      cgroup.subtree_control  dev-mqueue.mount               sys-kernel-debug.mount
cgroup.max.depth        cgroup.threads          init.scope                     sys-kernel-tracing.mount
cgroup.max.descendants  cpu.stat                io.stat                        system.slice
cgroup.procs            cpuset.cpus.effective   sys-fs-fuse-connections.mount  user.slice
cgroup.stat             cpuset.mems.effective   sys-kernel-config.mount`

**Comment by wywywywy** [comment]
On Pis the file to edit is `/boot/cmdline.txt` and it should look something like this:

`console=serial0,115200 console=tty1 root=PARTUUID=xxxxxxx rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory`

And on my own Pis the content of `/sys/fs/cgroup/` looks like this:
```
$ ls /sys/fs/cgroup/
blkio  cpu  cpuacct  cpu,cpuacct  cpuset  devices  freezer  memory  net_cls  net_cls,net_prio  net_prio  perf_event  pids  systemd  unified
```

**Comment by wywywywy** [comment]
I have now published a new image. It won't give you memory information until the memory cgroup is enabled, but at least it shouldn't crash.

**Comment by proggprod** [comment]
Excellent. I got sidetracked yesterday. I'm going to try this today.

**Comment by proggprod** [comment]
That all worked. Both bits.
I tried your new image and it didn't crash, but was still missing those mem stats. Then with the cmdline.txt edit, all metrics are now reporting.

Thank you. Good job.

**Comment by wywywywy** [comment]
Thank you very much. I'll close this issue now.
